# Generated by Django 2.0.13 on 2019-03-12 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_task', models.ManyToManyField(to='djangoApp.Task')),
                ('team_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
